### ISSUE TITLE
[hashicorp.terraform] Downloaded VS Code 1.47.3 into .vscode-test/vscode-1.47.3, Exit code: null, Done, Failed, Failed to run tests

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#113]
Auto-publishing failed with:

```
Executing prepublish script 'npm run vscode:prepublish'...

> terraform@2.1.1 vscode:prepublish /tmp/repository
> npm run test && npm run compile


> terraform@2.1.1 test /tmp/repository
> npm run test-compile && node ./out/test/runTest.js


> terraform@2.1.1 test-compile /tmp/repository
> tsc -p ./

Downloading VS Code 1.47.3 from https://update.code.visualstudio.com/1.47.3/linux-x64/stable
Downloaded VS Code 1.47.3 into .vscode-test/vscode-1.47.3
Exit code:   null
Done

Failed
Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terraform@2.1.1 test: `npm run test-compile && node ./out/test/runTest.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the terraform@2.1.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-08-11T03_24_04_270Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by jankeromnes** [comment]
@spoenemann any idea what could have gone wrong here, or what we could try as a fix?

**Comment by spoenemann** [comment]
When I try to build it on Gitpod I get

```
/workspace/vscode-terraform/.vscode-test/vscode-1.47.3/VSCode-linux-x64/code: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

The error comes from the [vscode-test](https://github.com/microsoft/vscode-test) package. We could either open an issue there and ask for support, or skip the tests for publishing.

How to skip the tests:
 * `echo "" > src/test/runTest.ts` before publishing
 * Check out https://github.com/hashicorp/vscode-terraform/commit/c2172872a74d069b52cf4e2912c564eb6e340921 instead of v2.1.1

**Comment by spoenemann** [comment]
Given that vscode-test is an official package for testing vscode extensions, this situation could easily occur for other extensions, too. One thing we could try is to install `libx11-dev` in the GitHub action VM as mentioned in the [vscode docs](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites).

**Comment by spoenemann** [comment]
> One thing we could try is to install libx11-dev in the GitHub action VM as mentioned in the vscode docs.

That doesn't help: https://github.com/spoenemann/vscode-extension-test-build/runs/971743575
