### ISSUE TITLE
Please upload the official language packs

### ISSUE THREAD

**Issue by GitMensch** [open-vsx/publish-extensions#117]
The language extensions found in https://github.com/Microsoft/vscode-loc are specific to a vscode release and therefore often updated. They are under MIT so publishing them in the registry is no issue license-wise.

Can you please contact the vscode-loc team and discuss the easiest way of integrating the 16 language packs (likely increasing in number) or would it be more reasonable to publish them directly here via CI?

**Comment by spoenemann** [comment]
Thanks for the request. @janbaltus @danyeh @weeteckt are you interested in publishing to the Open VSX Registry in addition to the VS Code Marketplace? The process is very similar to `vsce`, you'll find instructions here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by GitMensch** [comment]
Ping @spoenemann @janbaltus @danyeh @weeteckt - I'd really like to see those uploaded, ideally without an extra CI process here.
But if there's no other way I'd also appreciate an external CI here...

**Comment by spoenemann** [comment]
I think we can set up publishing here, and remove it again in case the maintainers would like to continue publishing.

@GitMensch would you like to create a PR? We need one entry in `extensions.json` for each language pack (see [README](https://github.com/open-vsx/publish-extensions#publish-extensions-to-open-vsx)), each with `id`, `repository` and  `location`.

**Comment by danyeh** [comment]
@spoenemann , please establish your own publish process. Feel free to take translation from vscode-loc.

**Comment by jankeromnes** [comment]
Hi @danyeh! OpenVSX already has its own publishing process, based on `vsce`:

- Either publish an extension yourself with a single command, `npx ovsx publish` (no need to install any dependency)
- Or add the extension to this very repository, our auto-publishing CI, and edit `extensions.json` to add the extension there (see README for the format, or use `node add-extension --download=VSIX_URL)

**Comment by GitMensch** [comment]
> @GitMensch would you like to create a PR?

I'll work on this now.

**Comment by spoenemann** [comment]
The overall build failure indicates that there are still extensions for which the automated publishing does not work for some reason. This does not affect the other extensions.
