### ISSUE TITLE
[ms-vscode.hexeditor]: please publish that

### ISSUE THREAD

**Issue by GitMensch** [open-vsx/publish-extensions#118]
I've seen multiple questions on this as it is highlighted in the user-visible changes of "VS Code" and when checking now seen that it is MIT-licensed.

Please add the CI for https://github.com/microsoft/vscode-hexeditor - thank you!

**Comment by spoenemann** [comment]
Thanks for the request. @lramos15 are you interested in publishing to the Open VSX Registry in addition to the VS Code Marketplace? The process is very similar to vsce, you'll find instructions here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by jankeromnes** [comment]
@GitMensch Good news! The Eclipse board may soon allow all "standard" open-source licensed extensions onto OpenVSX. While no official final decision has been announced yet, we consider this to be very promising, and have decided to accept `ms-vscode.hexeditor` now. Added in d53fee8b05fbd05b884ae05567deeab98b0e286f. Many thanks!

**Comment by jankeromnes** [comment]
Update: Publishing worked! 🎉 https://open-vsx.org/extension/ms-vscode/hexeditor
