### ISSUE TITLE
[ms-vscode.references-view] npm ERR! 404  'flatmap-stream@0.1.1' is not in the npm registry.

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#17]
Publishing the `ms-vscode.references-view` extension added in https://github.com/open-vsx/publish-extensions/pull/16 didn't work:

```
[FAIL] Could not process extension: {
  "id": "ms-vscode.references-view",
  "version": "0.0.4",
  "repository": "https://github.com/microsoft/vscode-references-view",
  "checkout": "0.0.4"
}
Error: Command failed: npm install

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz
npm ERR! 404 
npm ERR! 404  'flatmap-stream@0.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'repository'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

(See [full logs](https://github.com/open-vsx/publish-extensions/runs/532380660)).

**Comment by akosyakov** [comment]
I think we used wrong version, in Theia we tested this commit: https://github.com/microsoft/vscode-references-view/commits/05339da0c4d62d9804f9e33e47cafc2fcf1b2afa

cc @vince-fugnitto

**Comment by jankeromnes** [comment]
Maybe we should set this in `extensions.json`?

```json
    "checkout": "05339da0c4d62d9804f9e33e47cafc2fcf1b2afa"`
```

**Comment by akosyakov** [comment]
yes

**Comment by jankeromnes** [comment]
@akosyakov Ok, I can do the change, but note that I think this will publish version `0.0.47` and not `0.0.4`: https://github.com/microsoft/vscode-references-view/blob/05339da0c4d62d9804f9e33e47cafc2fcf1b2afa/package.json#L6
