### ISSUE TITLE
java extension is missing LS

### ISSUE THREAD

**Issue by akosyakov** [open-vsx/publish-extensions#18]
It is transferred from https://github.com/eclipse-theia/theia/issues/7448

**Comment by marcdumais-work** [comment]
Maybe related? https://github.com/redhat-developer/vscode-java/issues/1336

**Comment by jankeromnes** [comment]
The extension `redhat.java` was removed from `extensions.json` in https://github.com/open-vsx/publish-extensions/commit/be77f96166ea33ffd2cd0bf0e6a2eba6dcb1b11b

It is now published directly by RedHat, and version `0.59.1` should now include the Java Language Server: https://open-vsx.org/extension/redhat/java
