### ISSUE TITLE
ms-vscode.node-debug2 is missing

### ISSUE THREAD

**Issue by shahar-h** [open-vsx/publish-extensions#185]
[ms-vscode.node-debug2](https://github.com/microsoft/vscode-node-debug2) extension is missing although it's published to [openvsx](https://open-vsx.org/extension/ms-vscode/node-debug2).
It was there before: https://github.com/open-vsx/publish-extensions/commit/d9aed2d25d0da16aafd6d6e56402dfe0c358c66b.
Is there any reason it was removed?
There is a new patch(1.42.5) that I would like to use.

**Comment by spoenemann** [comment]
We removed it because the `ms-vscode` namespace has been claimed. But since the maintainers seem not to be interested in publishing to Open VSX, I think we can put the extension back into our list.

@shahar-h would you make a PR against extensions.json?

**Comment by shahar-h** [comment]
sure

**Comment by shahar-h** [comment]
Create a PR: #186

**Comment by shahar-h** [comment]
Resolved with #186
