### ISSUE TITLE
node-debug: incorrect version published due to typo

### ISSUE THREAD

**Issue by vince-fugnitto** [open-vsx/publish-extensions#19]
**Description**

Due to a [typo](https://github.com/open-vsx/publish-extensions/blob/master/extensions.json#L242) (`checkpoint` > `checkout`), and incorrect version of `node-debug` was published which is [incompatible with theia](https://github.com/eclipse-theia/theia/issues/7488). Would it be possible to replace the current `node-debug` version with the version that successfully works?

**Comment by spoenemann** [comment]
The previously published extension is deleted. The new version will be published at the next scheduled action run.

**Comment by vince-fugnitto** [comment]
> The previously published extension is deleted. The new version will be published at the next scheduled action run.

Do you know when the next scheduled run would be?
I don't see the `node-debug` builtin as of yet in open-vsx.

**Comment by spoenemann** [comment]
That's due to #20.
