### ISSUE TITLE
[streetsidesoftware.code-spell-checker] publish all add-on language dictionaries

### ISSUE THREAD

**Issue by geekley** [open-vsx/publish-extensions#195]
### streetsidesoftware.code-spell-checker-*
- publish each language and specialized dictionary add-on listed in the [README][1]
- if possible/necessary, auto-update URLs in the [README][1] to point to open-vsx.org instead of marketplace.visualstudio.com? @streetsidesoftware

[1]: https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/packages/client/README.md#add-on-language-dictionaries

**Comment by spoenemann** [comment]
Ideally the original maintainers would publish the extensions themselves. Could you create an issue at `vscode-spell-checker`? In case they are not willing to do it, we can add the extensions to the list here.
