### ISSUE TITLE
What happens to this service and its published extensions with the move to Eclipse?

### ISSUE THREAD

**Issue by GitMensch** [open-vsx/publish-extensions#221]
Given https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management I am curious what will happen here. The license is no issue, as only OSI-approved repos are added. I _guess_ that some of the entries for the CI may not have an appropriate license specifier in, so it may be needed to patch package.json before the build.
But the part that I wonder most: extension publishers need to register and as this repo's CI does the publishing will it be a registered extension publisher on its own? If not I guess the service will go down and every extension included here will be gone after the new terms get effective (the original authors specified they don't want to publish to open-vsx on their own, which was the reason for this service in the first place). If this CI is an own publisher or gets an exemption from the rules then it is just much easier for extension authors to not care about open-vsx themselves any more and tell people to register their extension here.

:-/

**Comment by spoenemann** [comment]
Details on this matter are still under discussion. I'll get back when we have a definite answer.

**Comment by spoenemann** [comment]
We will ensure conformance with the requirements of the Eclipse Foundation by

 * requiring all contributions to this repository to have an open source license (see [README](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension)),
 * signing the Publisher Agreement with the @open-vsx service account,
 * requiring all maintainers (currently @jankeromnes and me, but that will become more) to sign the Publisher Agreement.

With these measures in place, this repository and the extensions published through it will continue to be available.

CC @SharonCorbett

**Comment by GitMensch** [comment]
That's very good news, that you. I suggest to keep this issue open until January and pin it.

**Comment by GitMensch** [comment]
As the move to Eclipse is over and the questions raised here are not really relevant any more - closed.
