### ISSUE TITLE
[Suggestion] Faster CI by defaulting to yarn for everything

### ISSUE THREAD

**Issue by vinliao** [open-vsx/publish-extensions#226]
Hello people,

From what I see, the daily CI needs 30+ minutes to finish building and publishing. I haven't dive into the code yet, but maybe defaulting to `yarn` for everything might speed things up. 

Why? Because yarn caches the package so it doesn't have to re-download packages that it has previously downloaded.

And for the package that has package lock from npm, I think it can be removed and be replaced by yarn lock by running `yarn`.

**Comment by spoenemann** [comment]
If an extension has a `package-lock.json`, we need to respect it, otherwise we risk breaking the extension.

I don't think the long CI running time is really a problem: it runs only once a day anyway.

**Comment by vinliao** [comment]
Ah alright. Thanks for responding.
