### ISSUE TITLE
Maven extension missing

### ISSUE THREAD

**Issue by dr0i** [open-vsx/publish-extensions#242]
With https://github.com/open-vsx/publish-extensions/commit/784a105cbad5c15fa41b797cb6a30c48bf1550e4 the `maven` extension seems to be gone. Although it seems to still exist at https://open-vsx.org/extension/vscjava/vscode-maven . But if you click `changes` there the resource cannot be fetched.

So, this extension still available in `codium` in the openvsix-marketplace, but it logs in output->Language_Support_For_Java :

> fails to load extension bundle:
[...]
Contains: Cannot extract bundle symbolicName or version ~/.vscode-oss/extensions/vscjava.vscode-maven-0.21.2/jdtls.ext/com.microsoft.java.maven.plugin/target/com.microsoft.java.maven.plugin-0.21.2.jar

The extension "https://open-vsx.org/api/vscjava/vscode-maven/0.21.2/file/vscjava.vscode-maven-0.21.2.vsix" contains:

> extension/package.json:      "./jdtls.ext/com.microsoft.java.maven.plugin/target/com.microsoft.java.maven.plugin-0.21.2.jar"

which is missing.

This may be related to https://github.com/open-vsx/publish-extensions/issues/124 and https://github.com/eclipse-theia/theia/issues/7588.

**Comment by spoenemann** [comment]
It seems the extension has not been built correctly. We should fix that and then remove the old versions.
