### ISSUE TITLE
[jebbs.plantuml] Extension won't build under /tmp

### ISSUE THREAD

**Issue by marcdumais-work** [open-vsx/publish-extensions#272]
Troubleshooting in an environment similar to the publish bot, I could not build this extension, under `/tmp/extension`. When as a sanity check I tried the same under `/var/tmp/extension`, it worked. 

When building under `/tmp` we get a huge blob of `React`-related errors such as: 
```
> plantuml@2.14.1 buildsyntax /tmp/vscode-plantuml
> node ./scripts/build-syntax.js

../node_modules/@types/connect/index.d.ts:20:42 - error TS2689: Cannot extend an interface 'http.IncomingMessage'. Did you mean 'implements'?

20     export class IncomingMessage extends http.IncomingMessage {
                                            ~~~~~~~~~~~~~~~~~~~~

../node_modules/@types/react-virtualized/node_modules/@types/react/index.d.ts:2981:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

2981         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  ../node_modules/@types/react/index.d.ts:2982:14
    2982         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.

../node_modules/@types/react-virtualized/node_modules/@types/react/index.d.ts:2992:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.

```

See also: https://github.com/open-vsx/publish-extensions/pull/263

__update: How to reproduce:__

##  1) under /tmp

```bash
export OUTDIR=/tmp/repository
git clone --recurse-submodules https://github.com/qjebbs/vscode-plantuml.git $OUTDIR
cd $OUTDIR
wget -O plantuml.zip https://sourceforge.net/projects/plantuml/files/1.2021.0/plantuml-jar-mit-1.2021.0.zip/download && unzip plantuml.zip && rm plantuml.zip && mv COPYING COPYING.plantuml-jar
npm install && npm run compile
```
__Compilation errors expected, as per above__

## 2) not under /tmp

Try again but point OUTDIR to somewhere else. Make sure to use a path that's on the file system rather than e.g. a ramdrive or such (which might be causing the issue)

```bash
export OUTDIR=~/repository
git clone --recurse-submodules https://github.com/qjebbs/vscode-plantuml.git $OUTDIR
cd $OUTDIR
wget -O plantuml.zip https://sourceforge.net/projects/plantuml/files/1.2021.0/plantuml-jar-mit-1.2021.0.zip/download && unzip plantuml.zip && rm plantuml.zip && mv COPYING COPYING.plantuml-jar
npm install && npm run compile
```

__no compilation error expected__

**Comment by spoenemann** [comment]
@jankeromnes can you verify this? Shall we switch to another build directory?

**Comment by marcdumais-work** [comment]
@jankeromnes I have updated the description with easy instructions to reproduce the issue. They check-out on my local environment but I can only guess your build service is having the same issue.

**Comment by andhet** [comment]
I can confirm this.
The /tmp directory is mounted by several distributions with the noexec option.
During the compile phase _node_modules/.bin/tsc_ is run (a symlink to node_modules/typescript/bin/tsc), which isn't possible, because of the used noexec option.
Remounting /tmp with exec solves the problem.

If I look into the ubuntu-latest container image, I can't find that /tmp has an own mount point and / itself is mounted without noexec flag.
So there is another reason. It might be that an appamor profile is preventing from scripts run under /tmp. Appamor is active in the container, so that would be my best guess.

**Comment by jankeromnes** [comment]
Aha, great catch! Many thanks.

Might this potentially also explain https://github.com/open-vsx/publish-extensions/pull/286#issuecomment-779093302 and https://github.com/open-vsx/publish-extensions/pull/288#issuecomment-779094701?

Happy to switch to a different directory, e.g. home, to see if that fixes things.

**Comment by andhet** [comment]
Maybe. 
I have some spare time on wednesday. I will try to prove the hypothesis.

**Comment by andhet** [comment]
Ok, I've tested a few things and I was wrong. Builds fine under /tmp in the action. Since the latest version 2.14.0 is already published, and the plugin is compiling fine under the ubuntu container image used by the publish action... Can we close this now?

@jankeromnes 
> Might this potentially also explain [#286 (comment)](https://github.com/open-vsx/publish-extensions/pull/286#issuecomment-779093302) and [#288 (comment)](https://github.com/open-vsx/publish-extensions/pull/288#issuecomment-779094701)?
> 
> Happy to switch to a different directory, e.g. home, to see if that fixes things.
No, this extension doesn't build under home either. This is a another problem.

**Comment by marcdumais-work** [comment]
Thanks @andhet , closing.
