### ISSUE TITLE
node-debug: extension is not properly packaged

### ISSUE THREAD

**Issue by vince-fugnitto** [open-vsx/publish-extensions#28]
**Description**

The [vscode-node-debug](https://open-vsx.org/extension/ms-vscode/node-debug) is not properly packaged meaning that the extension does not work correctly when consumed. As a consequence, users are not able to successfully debug (including [running mocha tests](https://github.com/eclipse-theia/theia/issues/7488#issuecomment-619999485)).

From downloading the extension, it is clear that something went wrong as the entire `dist` folder is missing:

```
Error: Cannot find module '/Users/vincentfugnitto/workspace/theia/plugins/vscode-builtin-node-debug/extension/dist/nodeDebug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
root ERROR [hosted-plugin: 92007] internal/modules/cjs/loader.js:584
    throw err;
    ^
```

<div align='center'>

<img width="414" alt="Screen Shot 2020-04-27 at 10 09 24 AM" src="https://user-images.githubusercontent.com/40359487/80381637-3929a780-886f-11ea-934b-c7549ec37953.png">

</div>

**Comment by akosyakov** [comment]
@vince-fugnitto this extension namespace was claimed by MS, you will need to file an issue in vscode-node-debug and vscode-node-debug2 to ask them to release for Open VSX as well, since they are owner now

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto this extension namespace was claimed by MS, you will need to file an issue in vscode-node-debug and vscode-node-debug2 to ask them to release for Open VSX as well, since they are owner now
> 
> How to publish: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions


@akosyakov I wasn't aware that they had claimed the namespace and were interested in publishing to open-vsx :) I thought that since the extensions were builtins (and not usually published on the marketplace) we'd want to take care of publishing them ourselves, they are required for other plugins to work correctly.

Is there a standard way forward when requesting that they publish to open-vsx?

**Comment by akosyakov** [comment]
these extensions are published to MS marketplace:
- https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug
- https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2

**Comment by akosyakov** [comment]
> Is there a standard way forward when requesting that they publish to open-vsx?

Not yet, we wait till the registry is transfered to Eclipse Foundation.
