### ISSUE TITLE
hbenl.vscode-test-explorer, ms-python.python : missing "out" folder

### ISSUE THREAD

**Issue by marcdumais-work** [open-vsx/publish-extensions#29]
https://open-vsx.org/extension/hbenl/vscode-test-explorer

Normally after build it should have a `out` folder that contains the "executables" (.js files) for that extension, that gets packaged in the `.vsix`, but that's missing from what's published on open vsx. 

Building it locally, I was able to obtain that folder with these commands:
```
$> npm install 
$> npm run build
```

I see the [`npm install` is covered](https://github.com/open-vsx/publish-extensions/blob/master/publish-extensions.js#L66). I do not see that `npm run build` is called? 

If this is unexpected to be required, maybe a solution would be to support a field in `extensions.json` where one can add extra required command(s) to run to correctly build some extensions that need a bit more of a custom procedure, before the script proceeds to that packaging/publishing phase?

__update:__
for ms-python.python I was able to update the `out` folder like so:
```
$> npm install
$> npm run package
```

**Comment by jankeromnes** [comment]
Good catch, thanks @marcdumais-work.

@spoenemann Is `npm run build` or `yarn run build` typically a required step before publishing an extension?

If so, should it always be done explicitly before `ovsx publish`, or should `ovsx publish` take care of that?

**Comment by spoenemann** [comment]
No, not always. I think most extensions do that as part of the `prepare` step (i.e. during `yarn install`) or the `vscode:prepublish` step.

**Comment by marcdumais-work** [comment]
> No, not always. I think most extensions do that as part of the `prepare` step (i.e. during `yarn install`) or the `vscode:prepublish` step.

That's my experience as well. But since VS Code extensions are self-published, so long as the author knows how to get to a working package, it works. 

BTW, I think the same or similar thing was happening with extension `node-debug`: https://github.com/open-vsx/publish-extensions/issues/28 . That one as well I was able to get a working `.vsix`, IIRC by manually calling `npm install; npm build`.

**Comment by marcdumais-work** [comment]
I think `ms-python.python` has the same problem:
```
root INFO [hosted-plugin: 21414] PLUGIN_HOST(21414): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/vscode-builtin-python.vsix/extension/dist/pythonMain)
root INFO [hosted-plugin: 21414] PLUGIN_HOST(21414): PluginManagerExtImpl/loadPlugin(/home/<user>/.<prod>/extensions/ms-python.python-2020.2.3/extension/out/client/extension)
root ERROR [hosted-plugin: 21414] { Error: Cannot find module '/home/<user>/.<prod>/extensions/ms-python.python-2020.2.3/extension/out/client/extension'

The extension exists at that path, except from `out`. Another clueL the extension is a few hundred KB in size vs 40+ MB on GH release: https://github.com/microsoft/vscode-python/releases
```

**Comment by jankeromnes** [comment]
Fixed in https://github.com/open-vsx/publish-extensions/pull/36 by adding an extra `prepublish` option to the extension-publishing specification.

Also, I've added back `ms-python.python`, because the version on https://open-vsx.org is outdated (and broken due to missing `out` dir), and the namespace owner hasn't published anything yet.

I can also add back `node-debug` and `node-debug2`, but I'm not clear which of these are built-in (i.e. already published by your script @marcdumais-work).

**Comment by jankeromnes** [comment]
> I can also add back `node-debug` and `node-debug2`, but I'm not clear which of these are built-in

Ok, checked https://github.com/eclipse-theia/theia/blob/master/package.json again and found that `ms-python.python` is not built-in (i.e. I can add it back here), but `node-debug` and `node-debug2` are built-in (i.e. your script is already publishing them).

**Comment by marcdumais-work** [comment]
> `node-debug` and `node-debug2` are built-in (i.e. your script is already publishing them).

Nope. They are fetched by vscode's build and not packaged as builtin extensions AFAIK, unless maybe they're burred inside one of the builtin. So far we have a fork for these repos no theia-ide and build/publish them (to GH Releases) manually
