### ISSUE TITLE
Pyright extension

### ISSUE THREAD

**Issue by coxackie** [open-vsx/publish-extensions#292]
Right now, the [pyright](https://open-vsx.org/extension/ms-pyright/pyright) extension does not get updated, probably because of namespacing issues. Could open-vsx "adopt" it (as it is under an MIT licence), so that we can benefit from updated? Given the mess that the python extensions are right now, this one at least is both great, lightweight, and with a proper OS licence.

**Comment by jankeromnes** [comment]
Hi @coxackie, thanks for your suggestion! I agree it would make sense to auto-publish Pyright to OpenVSX from this repository.

In fact, the extension is already present in `extensions.json`:

https://github.com/open-vsx/publish-extensions/blob/4ddcda31a6a6064effdc21f03c33e8179e18be4f/extensions.json#L1029-L1035

However, the configuration seems to be broken, because auto-publishing [currently fails](https://github.com/open-vsx/publish-extensions/runs/1907790380?check_suite_focus=true) with:

```
Running: git clone --recurse-submodules https://github.com/Microsoft/pyright /tmp/repository
Running: git checkout 1.1.109
Running: npm install
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-pyright@1.1.109 vscode:prepublish /tmp/repository/packages/vscode-pyright
> node ./build/checkPackage.js && npm run clean && webpack --mode production --progress

Extension name must be "pyright", but is currently set to "vscode-pyright".
Please package by running "npm run package" to ensure the name is set correctly.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-pyright@1.1.109 vscode:prepublish: `node ./build/checkPackage.js && npm run clean && webpack --mode production --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-pyright@1.1.109 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by coxackie** [comment]
thanks for the prompt response. Could then someone please correct this, if it is just a problem of name mis-identification? (Also, latest version is 1.1.111 right now)

**Comment by jankeromnes** [comment]
Trying this potential fix: https://github.com/open-vsx/publish-extensions/commit/a3a6eacd197103973ea8ce582555aa4baaefbd34

Let's check tomorrow if tonight's CI run works better with this.

**Comment by coxackie** [comment]
It got updated, so that's good - many thanks! For future reference, does one have to manually update the version? Is latest version not pulled from github? I am asking because they seem to do frequent updates, and it would be a chore to have to update manually.

**Comment by jankeromnes** [comment]
> It got updated, so that's good

Thanks for the good news @coxackie! Could you please also confirm that the published extension works as expected?

> For future reference, does one have to manually update the version? Is latest version not pulled from github? I am asking because they seem to do frequent updates, and it would be a chore to have to update manually.

Any explicit version string found in `extensions.json` does need to be updated whenever the upstream extension publishes an update.

However, we've partly automated the process of checking GitHub for updates (either in tags or GitHub Releases) and updating `extensions.json`, and this automation runs every week on Sunday, producing Pull Requests like this one: https://github.com/open-vsx/publish-extensions/pull/290

I believe Pyright updates should be detected & handled automatically.

**Comment by coxackie** [comment]
yes, it works, same as when I downloaded manually VSIX. many thanks. Feel free to close this.
