### ISSUE TITLE
Help: publish lua-language-server

### ISSUE THREAD

**Issue by coxackie** [open-vsx/publish-extensions#295]
I followed the instructions for https://github.com/sumneko/lua-language-server (the author has unfortunately not responded in request to publish to openvsx, the licence is MIT), but I get
```
gitpod /workspace/publish-extensions $ node add-extension https://github.com/sumneko/lua-language-server --checkout
Scraping https://github.com/sumneko/lua-language-server/releases to check for updates...
Running: git clone --recurse-submodules https://github.com/sumneko/lua-language-server /tmp/repository
Running: ls package.json 2>/dev/null || git ls-files | grep package\.json
[FAIL] Could not add https://github.com/sumneko/lua-language-server!
Error: Command failed: ls package.json 2>/dev/null || git ls-files | grep package\.json

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ls package.json 2>/dev/null || git ls-files | grep package\\.json',
  stdout: '',
  stderr: ''
}
Running: rm -rf /tmp/repository
```
Anyone knows what is wrong?

**Comment by jankeromnes** [comment]
Hi @coxackie! Oh, thank you for finding what looks like a bug in the `add-extensions` script.

It seems to be unable to locate the extension's `package.json` file in that repository. I'll have a look.

**Comment by coxackie** [comment]
@jankeromnes sure thing, did not do anything, just followed instructions.

**Comment by coxackie** [comment]
The author has now kindly published the extension in OpenVSX. This issue can be closed, unless @jankeromnes wants to leave it open for whatever bug in the `add-extensions` is there to be fixed.

**Comment by jankeromnes** [comment]
Ah, that's perfect. Many thanks @coxackie for helping make this happen! 💯
