### ISSUE TITLE
clang extension not getting updated

### ISSUE THREAD

**Issue by coxackie** [open-vsx/publish-extensions#310]
According to https://github.com/clangd/vscode-clangd/releases/tag/v0.1.11 there is already 0.1.11 out, but https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd is still stuck at 0.1.9. Any ideas of what the problem may be?

**Comment by marcdumais-work** [comment]
I think @planger took care of publishing `v0.9.1`. Maybe he can publish the latest version.

**Comment by planger** [comment]
I've now published [`v0.1.10`](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd/0.1.10) and [`v0.1.11`](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd/0.1.11).

**Comment by filiptronicek** [comment]
Looks like this is indeed not an issue anymore, closing :)
