### ISSUE TITLE
CI doesn't process `felixfbecker.php-intellisense` extension properly

### ISSUE THREAD

**Issue by alefbragin** [open-vsx/publish-extensions#315]
Package of `felixfbecker.php-intellisense` are broken. It does not contain extension's build itself and LSP server.

It looks like problems with the extension building were earlier. Most recent [commit](https://github.com/open-vsx/publish-extensions/commit/5b97679e43ee9c422335797a8624e047a5969217) involving `felixfbecker.php-intellisense` turns to direct downloading for it. But the [package](https://open-vsx.org/api/felixfbecker/php-intellisense/2.3.14) timestamp (obtained by `curl "https://open-vsx.org/api/felixfbecker/php-intellisense/2.3.14" | jq .timestamp`) is `2020-07-10T13:22:40Z` that earlier than the commit date (`2020-08-28T19:56:03Z`). It seems CI doesn't process the commit properly.

Currently package from [open-vsx.org](https://open-vsx.org/extension/felixfbecker/php-intellisense) is differ from ones from [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) or from [GitHub releases](https://github.com/felixfbecker/vscode-php-intellisense/releases/download/v2.3.14/php-intellisense.vsix).

**Comment by filiptronicek** [comment]
@alefbragin could you please reiterate what you think the problem is here? In this case, the CI doesn't "process" any commit at all, it just downloads the `.vsix` file from the releases, unpacks it and publishes that to OpenVSX.
