### ISSUE TITLE
[austin.code-gnu-global] Error: SVGs can't be used as icons: logo.svg

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#33]
```
[FAIL] Could not process extension: {
  "id": "austin.code-gnu-global",
  "version": "0.2.2",
  "repository": "https://github.com/austin-----/code-gnu-global"
}
Error: SVGs can't be used as icons: logo.svg
    at validateManifest (/home/runner/work/publish-extensions/publish-extensions/node_modules/vsce/out/package.js:554:15)
```

This makes me very sad. SVGs should definitely be supported.

**Comment by spoenemann** [comment]
SVGs are a security risk: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions

**Comment by jankeromnes** [comment]
Today I learned that you can add JavaScript code to your SVGs. 🤦

**Comment by filiptronicek** [comment]
@jankeromnes this extension seems to not be present anymore in the extensions file, is this ok to close?

**Comment by jankeromnes** [comment]
Oops, indeed: https://github.com/open-vsx/publish-extensions/commit/9a2eadfedb51948559aaf432284d105549bb4708

Fine to close then. 👍
