### ISSUE TITLE
alefragnani.bookmarks is not available

### ISSUE THREAD

**Issue by alexitx** [open-vsx/publish-extensions#347]
Old version 12.1.0 is present in `extensions.json`, the latest is 13.0.4.
https://open-vsx.org/extension/alefragnani/bookmarks leads to "Extension Not Found".

**Comment by jankeromnes** [comment]
Hi @alexitx!

Unfortunately, `alefragnani.Bookmarks` cannot be published to OpenVSX because some of its code is not open-source: https://github.com/alefragnani/vscode-bookmarks/issues/315

**Comment by alexitx** [comment]
Is there an alternative I can use before resorting to installing `vsix` manually? I couldn't find anything similar on Open VSX.

**Comment by jankeromnes** [comment]
Ah, sorry, I overlooked the fact that GitHub Releases (now) have `.vsix` files: https://github.com/alefragnani/vscode-bookmarks/releases

In this case, I think we can stop [preventing](https://github.com/open-vsx/publish-extensions/blob/d2ba5125b02b8c2250aab97472f3ac5f803b0efe/upgrade-extensions.js#L20) auto-upgrades for this extension, and the upgrade script should automatically do the right thing. I'll try that now.

**Comment by jankeromnes** [comment]
@alexitx: Update: I've re-enabled auto-publishing of `alefragnani.Bookmarks` to OpenVSX.

This means that, tonight at 03:03 UTC, the regular auto-publish job should re-publish `alefragnani.Bookmarks` to OpenVSX.

We'll know tomorrow if this worked or if there was some other problem. Many thanks for bringing this up! 🙏
