### ISSUE TITLE
Python extension outdated

### ISSUE THREAD

**Issue by petoknm** [open-vsx/publish-extensions#358]
2020.10.332292344 on https://open-vsx.org/extension/ms-python/python
and 
2021.5.926500501 on https://marketplace.visualstudio.com/items?itemName=ms-python.python
and
2021.5.842923320 on https://github.com/open-vsx/publish-extensions/blob/d070a30881a7c27352e9c2c078642a66c5789e98/extensions.json#L1131 which is fine because latest version was releases 22 hours ago

**Comment by yimuchen** [comment]
I dug around in the action log. It seems to be an issue with the `ms-python.python` extension requiring the `jupyter` extension by default. I think there are a couple of pull requests aimed to solve related issues: 

- Removing jupyter as dependency of ms-python (outdated?):  https://github.com/open-vsx/publish-extensions/pull/293
- Adding jupyter to the repository (stuck with license issue on upstream side?): https://github.com/open-vsx/publish-extensions/pull/269

Not sure if these can be easily resolved soon. 

Full actions log regarding the ms-python.python package:
```
Processing extension: {
  "id": "ms-python.python",
  "download": "https://github.com/microsoft/vscode-python/releases/download/2021.5.842923320/ms-python-release.vsix",
  "version": "2021.5.842923320"
}
Checking Open VSX version of ms-python.python
Found version: 2020.10.332292344
Attempting to publish ms-python.python to Open VSX
Creating Open VSX namespace failed -- assuming that it already exists
Error: Namespace already exists: ms-python
    at IncomingMessage.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/registry.js:173:40)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Downloading https://github.com/microsoft/vscode-python/releases/download/2021.5.842923320/ms-python-release.vsix
[FAIL] Could not process extension: {
  "id": "ms-python.python",
  "download": "https://github.com/microsoft/vscode-python/releases/download/2021.5.842923320/ms-python-release.vsix",
  "version": "2021.5.842923320"
}
Error: Cannot resolve dependency: ms-toolsai.jupyter
    at IncomingMessage.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/registry.js:173:40)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Running: rm -rf /tmp/repository /tmp/download
```

**Comment by petoknm** [comment]
Issue is `Error: Cannot resolve bundled extension: ms-toolsai.jupyter`.

Can we ignore the bundled extension? AFAIK, it should be optional now.

<details>
  <summary>Build Log</summary>

```
Processing extension: {
  "id": "ms-python.python",
  "download": "https://github.com/microsoft/vscode-python/releases/download/2021.6.944021595/ms-python-release.vsix",
  "version": "2021.6.944021595"
}
Checking Open VSX version of ms-python.python
Found version: 2020.10.332292344
Attempting to publish ms-python.python to Open VSX
Creating Open VSX namespace failed -- assuming that it already exists
Error: Namespace already exists: ms-python
    at IncomingMessage.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/registry.js:176:40)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Downloading https://github.com/microsoft/vscode-python/releases/download/2021.6.944021595/ms-python-release.vsix
[FAIL] Could not process extension: {
  "id": "ms-python.python",
  "download": "https://github.com/microsoft/vscode-python/releases/download/2021.6.944021595/ms-python-release.vsix",
  "version": "2021.6.944021595"
}
Error: Cannot resolve bundled extension: ms-toolsai.jupyter
Running: rm -rf /tmp/repository /tmp/download
    at IncomingMessage.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/registry.js:176:40)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
</details>

**Comment by omhomurlu** [comment]
It's released with optional jupyter extension dependency with the latest release: https://github.com/microsoft/vscode-python/releases/tag/2021.6.944021595
_Move the Jupyter extension from being a hard dependency to an optional one, and display an informational prompt if Jupyter commands try to be executed from the Start Page._

I've tried installing linked https://github.com/microsoft/vscode-python/releases/download/2021.6.944021595/ms-python-release.vsix and it works without jupyter extension.

**Comment by mpnordland** [comment]
This issue is still occurring. I am unable to install the python extension from Open-VSX because the Jupyter extension is out of date and not compatible with VS Code 1.58.0

**Comment by akosyakov** [comment]
Please upgrade to latest VS Code. Unfortunately publishing script for python was broken for 8 months, so many intermediate were not published. Now it is fixed and new versions are published, but you have to have up to date VS Code to use them.
