### ISSUE TITLE
latex-workshop version 8.20.2 is broken

### ISSUE THREAD

**Issue by exploide** [open-vsx/publish-extensions#414]
Since the update to latex-workshop version 8.20.2, the extension does no longer work. The build command for example is broken. It isn't even possible to type newlines because of an error saying "command 'latex-workshop.onEnterKey' not found".

This has been reported upstream https://github.com/James-Yu/LaTeX-Workshop/issues/2845 but it was explained that it is an issue with open-vsx:

> The James-Yu.latex-workshop-8.20.2.vsix file at open-vsx does not include extension/out/src/main.js. The .vsix file is invalid. And, we don't publish the file at open-vsx. The admin of open-vsx publishes the file independently of us.

**Comment by jemand771** [comment]
here's the corresponding actions log. I don't see anything wrong with it though 🤔 
https://github.com/open-vsx/publish-extensions/runs/3407072828?check_suite_focus=true#step:7:5595 (the link takes a while to load and auto-scroll)

**Comment by l1ving** [comment]
Can confirm that building it manually works fine. Seeing as `vsce` has been bumped to the latest version, what is actually blocking things from working now? https://github.com/eclipse/openvsx/blob/2ce0e286df21fae0255d482be47c174049702ccf/cli/package.json#L44

**Comment by jankeromnes** [comment]
@l1ving Thanks for noticing and confirming!

The latest publish run says this:

```
Processing extension: {
  "id": "James-Yu.latex-workshop",
  "repository": "https://github.com/James-Yu/LaTeX-Workshop",
  "version": "8.20.2",
  "checkout": "v8.20.2",
  "prepublish": "npm run compile"
}
Checking Open VSX version of James-Yu.latex-workshop
Found version: 8.20.2
[SKIPPED] Requested version 8.20.2 is already published on Open VSX
```

If the currently-uploaded version `8.20.2` is broken, we'll need to either wait for the next release of `James-Yu.latex-workshop` to publish a fixed version, or we can request that an OpenVSX admin deletes the currently-broken `8.20.2` artifact so that it can be re-published successfully.

**Comment by jankeromnes** [comment]
Hi @spoenemann! What is the current process to get a broken extension versions deleted from OpenVSX? (Specifically `James-Yu.latex-workshop@8.20.2`)

**Comment by brianking** [comment]
@jankeromnes You can file an issue at https://github.com/EclipseFdn/open-vsx.org/issues to remove extensions.

**Comment by l1ving** [comment]
Thank you for following up, glad to here there isn't much of an issue at this point :)

**Comment by brianking** [comment]
> If the currently-uploaded version `8.20.2` is broken, we'll need to either wait for the next release of `James-Yu.latex-workshop` to publish a fixed version, or we can request that an OpenVSX admin deletes the currently-broken `8.20.2` artifact so that it can be re-published successfully.

v8.20.2 has been removed.

**Comment by jemand771** [comment]
thanks! the extension should rebuild in about 12 hours from now, hopefully we'll get a working 8.20.2 out of that :)

**Comment by jemand771** [comment]
for me it looks like all of the weird issues the broken vsix file had are gone now - can someone else confirm that? ^^

**Comment by arnaudgolfouse** [comment]
Installing manually the .vsix file at https://open-vsx.org/extension/James-Yu/latex-workshop works for me, but it doesn't via codium... is that to be expected ?

**Comment by arnaudgolfouse** [comment]
Well nevermind, it works now 🎉

**Comment by exploide** [comment]
Thanks, it's working. I'm closing this issue then.
