### ISSUE TITLE
Jupyter can not be installed

### ISSUE THREAD

**Issue by groengpx** [open-vsx/publish-extensions#433]
The current Jupyter extension on open-vsx.org requires vscode 1.59-insider:

```extension.vsixmanifest
<Property Id="Microsoft.VisualStudio.Code.Engine" Value="1.59.0-insider" />
```

This makes it impossible the install the extension on vscod{e,ium} 1.60 (not insider).

**Comment by BartG95** [comment]
As of today, it works again: I can install the Jupyter extension on vscodium 1.60 (not insider), without any errors or warnings.
Whoever solved this: thanks! This issue can be closed.
