### ISSUE TITLE
Add some VS Code-recommended extensions to Open VSX

### ISSUE THREAD

**Issue by filiptronicek** [open-vsx/publish-extensions#476]
Not all non-proprietary extensions, which VS Code recommends for specific files and languages are published to Open VSX, from what I found those are
- [`ms-vscode.vscode-github-issue-notebooks`](https://github.com/microsoft/vscode-github-issue-notebooks)
~[`ms-dotnettools.csharp`](https://github.com/OmniSharp/omnisharp-vscode)~
~[`ms-vscode.cpptools`](https://github.com/microsoft/vscode-cpptools/tree/main/Extension)~

Would be great to have them published, so they can be used, they are extensions with big user bases.

**Comment by akosyakov** [comment]
I think ms-dotnettools.csharp and ms-vscode.cpptools has runtime deps to proprietary components like debuggers which cannot be used outside of MS products, so they cannot be published to Open VSX as well. 

`ms-vscode.vscode-github-issue-notebooks` looks good.

**Comment by filiptronicek** [comment]
Thanks for the note, @akosyakov, I'll update the issue accordingly.

**Comment by seanking2919** [comment]
For note, @muhammadsammy already publishes and maintains a [FOSS-licensed version of the C# extension for VS Code](https://open-vsx.org/extension/muhammad-sammy/csharp) on Open VSX. As far as the C/C++ one, there seems to be no alternative version yet on Open VSX.

**Comment by akosyakov** [comment]
resolved with https://github.com/open-vsx/publish-extensions/pull/505
