### ISSUE TITLE
dbaeumer.vscode-eslint is outdated

### ISSUE THREAD

**Issue by akosyakov** [open-vsx/publish-extensions#482]

**Comment by akosyakov** [comment]
I think we should switch to tags instead of GitHub releases in this case: https://github.com/microsoft/vscode-eslint/tags

**Comment by filiptronicek** [comment]
@akosyakov trying to create a way of automating the process of figuring out whether a repo hasn't moved away from GH Releases.

**Comment by filiptronicek** [comment]
We could have a query like this to check whether the latest tag was published as a release: 
```gql
query GetLatestTagAndRelease {
  repository(name: "vscode-eslint", owner: "microsoft") {
    refs(refPrefix: "refs/tags/release/", first: 1, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
      edges {
        node {
          name
        }
      }
    }
    releases(first: 1) {
      edges {
        node {
          tagName
        }
      }
    }
  }
}

```

**Comment by akosyakov** [comment]
I thought we already have a logic based on tags: https://github.com/open-vsx/publish-extensions/blob/7d08a64dcc8e4542c260e2332fcab1c7b2994250/add-extension.js#L137-L146

It should be a matter of adding checkout in extensions.json?
