### ISSUE TITLE
Open in vscodium

### ISSUE THREAD

**Issue by yashpalgoyal1304** [open-vsx/publish-extensions#484]
i am certain that this issue doesnt belong in this repo, but i didnt find any website repo ([any other repo](https://github.com/open-vsx?tab=repositories) for that matter), so, posting here.

- It would be really nice if the open-vsx site has some mechanism to trigger "Open in VSCodium" behaviour 
- found in other sites, including the ms-vsmarket site, or telegram site.

Rough mockup:

<img src="https://user-images.githubusercontent.com/19423063/140738816-876d89c7-32ed-41a8-a9ef-9b52e7bdb843.png" height="320px">

### References:
* MS-vsMarket:
![open in VS Code vivaldi_8o5kd0soPu](https://user-images.githubusercontent.com/19423063/140739109-5932d3fc-baab-4b91-8968-61c340994884.png)
* Telegram:

https://user-images.githubusercontent.com/19423063/140739460-16c19e72-3144-4e2f-91c8-7775211dd36f.mp4

**Comment by akosyakov** [comment]
You should open an issue here instead: https://github.com/eclipse/openvsx Although I am not sure where we should stop then, VSCodium is not a single consumer of Open VSX, neither primary. Why should it be special? Should we allow any fork of VS Code, i.e. Gitpod, openvscode-server, code-sever, any Theia based product?
