### ISSUE TITLE
Add hadolint (GPL-3.0)

### ISSUE THREAD

**Issue by Kreyren** [open-vsx/publish-extensions#49]
https://github.com/hadolint/hadolint

https://marketplace.visualstudio.com/items?itemName=exiasr.hadolint

**Comment by Kreyren** [comment]
cc @jankeromnes

**Comment by jankeromnes** [comment]
Interesting, thanks!

But I don't think that GPL-3 licensed extensions can be used on Open VSX yet -- @spoenemann do you know?

**Comment by spoenemann** [comment]
Right. We haven't built in any technical restriction regarding the license yet, but we'll do that as the transfer to the Eclipse Foundation gets forward. The admissible licenses are Apache-2.0, EPL-2.0, MIT, ISC, BSD-2-Clause, BSD-3-Clause. But you can contact license@eclipse.org to determine if another license, like GPL-3, is acceptable.

**Comment by Kreyren** [comment]
Why wouldn't the license that basically built the open-source be acceptable here? :thinking:

**Comment by spoenemann** [comment]
I don't know, but I'm sure the Eclipse Foundation has good reasons for it. You could ask via the email address posted above.

**Comment by Kreyren** [comment]
Email sent 

On June 19, 2020 11:10:49 AM GMT+02:00, "Miro Spönemann" <notifications@github.com> wrote:
>I don't know, but I'm sure the Eclipse Foundation has good reasons for
>it. You could ask via the email address posted above.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-vsx/publish-extensions/issues/49#issuecomment-646527007

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jankeromnes** [comment]
Since we haven't heard back yet, I've also asked about GPL-3.0 (since I was emailing Eclipse about another license anyway).

This is the official response:

> Thanks for checking in with us.  Unfortunately no, the GPL (any version) is not acceptable because of license incompatibility reasons. Many years ago the FSF and the Eclipse Foundation jointly [published guidance](https://eclipse-foundation.blog/2010/04/06/epl-gpl-commentary/) regarding the use of the GPL for plugins, and this guidance would apply to OpenVSX extensions as well.  
> 
> The following are the Eclipse Board Approved license information for OpenVSX extensions:
> 
> Registry Code Content Offerings will be subject to one or more of the following licenses:
> 
> EPL-2.0, Apache-2.0, MIT, ISC, BSD-2-Clause or BSD-3-Clause (collectively, “Permitted Code Licenses”).
> 
> Non-Code Content will be subject to one of the above licenses for Code Content, or one of the following licenses: CC-BY-SA-3.0, CC-BY-3.0, CC-BY-SA-4.0 or CC-By-4.0.

So, unfortunately, we cannot accept GPL-licensed extensions into https://open-vsx.org at the moment. Sorry about that. :/

**Comment by mattburgess** [comment]
I am most definitely not a lawyer, but from that same blog post linked to above:

> Under the terms of the EPL, it appears that it may be possible to license plug-ins under the GPL. What is clear, however, is that it is not possible to link a GPL-licensed plug-in to an EPL-licensed code and distribute the result. Any GPL-licensed plug-in would have to be distributed independently and combined with the Eclipse platform by an end user. This is why, for example, the Eclipse Foundation has allowed the independent distribution of GPL-licensed plug-ins via our Eclipse Marketplace.

That makes the strong wording of the rest of that email response you got a little odd to me. Surely the Eclipse Marketplace and the OpenVSX Registry are providing a very similar service and therefore either both or none should be permitted to distribute GPL licensed plugins?

Also from that blog post:

> In other words, it appears that it is the position of the FSF that since your plug-in was designed to run on top of the Eclipse platform it doesn’t matter if they’re distributed separately: the GPL should not be used for licensing Eclipse plug-ins.

But FSF's position doesn't hold here either. The plugins hosted on OpenVSX will have been designed to work on top of the VSCode platform, not the Eclipse platform. VSCode is MIT licensed, and the GPL and MIT are compatible so it's understandable why VSCode plugin authors would choose to license their code under the GPL.

Note that MIT licensed plugins are permitted into OpenVSX according to your email response. Again, given that the GPL and MIT are compatible, it seems odd to me that the Eclipse Foundation would prevent GPL extensions from being added to the registry.

**Comment by jankeromnes** [comment]
Publishing worked! 🎉 https://open-vsx.org/extension/exiasr/hadolint
