### ISSUE TITLE
Update entry for formulahendry.auto-rename-tag

### ISSUE THREAD

**Issue by mellson** [open-vsx/publish-extensions#490]
[formulahendry.auto-rename-tag](https://github.com/formulahendry/vscode-auto-rename-tag) has stopped releasing on their repo and now do it directly to the vs code marketplace. So we need to update our entry and build it from source.

**Comment by filiptronicek** [comment]
This should be fixed by https://github.com/open-vsx/publish-extensions/pull/494.
