### ISSUE TITLE
Add support for GitLab repositories for extensions

### ISSUE THREAD

**Issue by filiptronicek** [open-vsx/publish-extensions#503]
Currently, all releases, versions and tags are fetched using octokit.js, but this doesn't allow for GitLab, so support for this should be added.

**Comment by filiptronicek** [comment]
- https://github.com/open-vsx/publish-extensions/blob/master/extensions.json#L498
- https://github.com/open-vsx/publish-extensions/blob/master/extensions.json#L593
- https://github.com/open-vsx/publish-extensions/blob/master/extensions.json#L597
- https://github.com/open-vsx/publish-extensions/blob/master/extensions.json#L1493

**Comment by bigint** [comment]
Maybe I can pick this 😄

**Comment by filiptronicek** [comment]
As @bigint pointed out, we can use https://github.com/jdalrymple/gitbeaker to access the GitLab API via JS.

**Comment by akosyakov** [comment]
@bigint It should be integrated here https://github.com/open-vsx/publish-extensions/blob/master/lib/resolveExtension.js

**Comment by akosyakov** [comment]
Wait a bit working on it, I think we need to rewrite it to use local git to ask questions about tags and commits instead of GitHub apis. Jobs are hitting rate limit.

**Comment by bigint** [comment]
Makes sense, rate limits are bad 😭

**Comment by akosyakov** [comment]
Pushed a commit fixing, so it should be quite easy, the only code which should be aligned with GitLab is https://github.com/open-vsx/publish-extensions/blob/66c6d4697c017b4262cbb40d6bc7d138caadbcde/lib/resolveExtension.js#L71-L92 Otherwise it will use local git.

**Comment by akosyakov** [comment]
@bigint Are you looking into it? Or @filiptronicek can take it?

**Comment by bigint** [comment]
I'm bit busy RN, yes @filiptronicek can take it 😄
