### ISSUE TITLE
smoke test extension with latest OpenVSCode server before publishing

### ISSUE THREAD

**Issue by akosyakov** [open-vsx/publish-extensions#507]
@jeanp413 do you think it is possible? Can we reuse your tool to run tests against openvscode server?

Basically I want to run code cli to install from vsix, then open a window with plawright and check whether extension is installed and does not fail while activating.

**Comment by loujaybee** [comment]
This was currently in groundwork inbox, moving to scheduled for now.

**Comment by jeanp413** [comment]
@akosyakov yeah I think it's possible but for this case I think It'll easier to just use the oficial test utility https://github.com/microsoft/vscode-test

**Comment by akosyakov** [comment]
@filiptronicek maybe you can also look into it?

**Comment by filiptronicek** [comment]
> @filiptronicek maybe you can also look into it with guidance from @jeanp413 ?

I'd be delighted to.
