### ISSUE TITLE
draw.io extension (GPL-3.0)

### ISSUE THREAD

**Issue by hallvard** [open-vsx/publish-extensions#51]
I would like to integrate draw.io into gitpod, e.g. using this extension: https://github.com/hediet/vscode-drawio

This particular one failed with en error related to registerCustomEditorProvider is not a function. I'm guessing it is using new API for registering custom editors that is not official or not supported by gitpod.

**Comment by jankeromnes** [comment]
Hi @hallvard!

> I would like to integrate draw.io into gitpod, e.g. using this extension: https://github.com/hediet/vscode-drawio

I wouldn't mind automatically publishing this extension to https://open-vsx.org, except that I don't think GPL-3 extensions are compatible yet, cc @spoenemann (same problem as https://github.com/open-vsx/publish-extensions/issues/49).

> This particular one failed with en error related to registerCustomEditorProvider is not a function. I'm guessing it is using new API for registering custom editors that is not official or not supported by gitpod.

Ah, that could indeed be the case. For VS Code API compatibility issues in Gitpod or Theia, please open an issue in https://github.com/eclipse-theia/theia/issues (providing the extension you tried and the error you got is super helpful, thanks).

**Comment by jankeromnes** [comment]
@hallvard Good news! The Eclipse board may soon allow all "standard" open-source licensed extensions onto OpenVSX. While no official final decision has been announced yet, we consider this to be very promising, and have decided to accept the draw.io extension now. Added in f4a8b067a57e7a716c27403bfc1e184b28c3848d. Many thanks for your patience!

**Comment by hallvard** [comment]
Nice! Does this mean that the custom editor extension is implemented so this extension actually works? It doesn't seem so from the corresponding issue #6636.

**Comment by spoenemann** [comment]
That's a Theia issue. This repository is only about publishing extensions.

**Comment by spoenemann** [comment]
@jankeromnes looking at the [package.json](https://github.com/hediet/vscode-drawio/blob/6376917d1c7702a7cf53b33fa3408a27219c786b/package.json#L221) it seems you need to add a `yarn pre-build` prepublish command.

Should we also add a section to our README.md about checking prepublish requirements of extensions?

**Comment by jankeromnes** [comment]
> @jankeromnes looking at the package.json it seems you need to add a yarn pre-build prepublish command.

Aha, thanks for catching that!

> Should we also add a section to our README.md about checking prepublish requirements of extensions?

We could. Do you have a general process that you follow to check these? (My process is looking at "scripts" in package.json, and seeing if there is something called "compile" or "build" or "package" that isn't covered by "vscode:prepublish", but maybe that's not the best way.)

**Comment by spoenemann** [comment]
> looking at "scripts" in package.json, and seeing if there is something called "compile" or "build" or "package" that isn't covered by "vscode:prepublish"

:+1:

**Comment by jankeromnes** [comment]
Publishing worked! 🎉 https://open-vsx.org/extension/hediet/vscode-drawio

But the version string is `999.0.0-alpha`.

**Comment by spoenemann** [comment]
> But the version string is 999.0.0-alpha.

Looks like there is a missing build step, but I can't see that from the package.json.

**Comment by hediet** [comment]
Author of the Draw.io extension here. I setup a CI step so that whenever the extension is published to the VS Code marketplace, it is also published to open-vsx!
So no external auto publish should be required anymore.

> But the version string is 999.0.0-alpha.

I setup CI to extract the version from the changelog.
The version in package.json is 999.0.0-alpha so that, when I debug my extension, it is never overwritten by any installed extension.
