### ISSUE TITLE
openvsx extension missing included npm_modules

### ISSUE THREAD

**Issue by matkoniecz** [open-vsx/publish-extensions#512]
PeterWone/vsc-print extensions fails to install in VSCodium what is caused by corruption of extension package by openvsx

I am not the first affected person, see https://github.com/PeterWone/vsc-print/issues/116

I reported it as VScodium bug but appears to be openvsx bug, see https://github.com/VSCodium/vscodium/issues/928

entire `node_modules` was missing.

It is also missing from VSIX file at https://open-vsx.org/extension/pdconsec/vscode-print

It is not missing from VSIX file at https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print

> Published by open-vsx

so I am reporting it here

**Comment by matkoniecz** [comment]
pure guessing:

Maybe https://github.com/PeterWone/vsc-print/blob/master/.vscodeignore#L23 is not parsed?

See also https://github.com/eclipse/openvsx/issues/376#issuecomment-978318544 by extension author:

> In respect of @matkoniecz speculation that [.vscodeignore#L23 ](https://github.com/PeterWone/vsc-print/blob/master/.vscodeignore#L23) is not parsed - Microsoft briefly changed the way this file was parsed to make it consistent with other things. I raised [an issue about problems this caused](https://github.com/microsoft/vscode-vsce/issues/587) and the outcome was they reverted the change.
> 
> It is possible that this change and reversion has contributed.

**Comment by matkoniecz** [comment]
See also:

- material theme extension is missing build folder #196 
- Missing out/ directory #163

**Comment by akosyakov** [comment]
Extension was removed from OpenVSX as requested by the author: https://github.com/eclipse/openvsx/issues/377
Please up-vote instead: https://github.com/PeterWone/vsc-print/issues/120

**Comment by matkoniecz** [comment]
> Extension was removed from OpenVSX as requested by the author: eclipse/openvsx#377

If I read it correctly author is fine with publishing version obeying MIT license - and that is not fatally broken while being attributed to them.

**Comment by akosyakov** [comment]
The author asked explicitly to take it down from auto publishing and going to publish himself instead: https://github.com/eclipse/openvsx/issues/377#issuecomment-978914061

**Comment by AS400JPLPC** [comment]
please install accès  https://open-vsx.org/?search=&category=&sortBy=relevance&sortOrder=desc
Thank
