### ISSUE TITLE
[matklad.rust-analyzer] Extension autopublish killed by an upstream change

### ISSUE THREAD

**Issue by Mazwak** [open-vsx/publish-extensions#527]
A change in extension publishing killed auto publish.

See https://github.com/rust-analyzer/rust-analyzer/issues/11080

**Comment by akosyakov** [comment]
@filiptronicek Can you guide authors to remove an extension from here and let them to publish directly? I think it would be the best and align with https://github.com/open-vsx/publish-extensions#when-to-add-an-extension

**Comment by Mazwak** [comment]
For the record
Direct publish declined by maintainer on July 2020 in https://github.com/rust-analyzer/rust-analyzer/issues/4936
Things changed in 2021 in https://github.com/rust-analyzer/rust-analyzer/issues/7284
but it is blocked by https://github.com/eclipse/openvsx/issues/336

To users that want an updated RA in their vscode clone, you have to install the vsix release for the time being
https://github.com/rust-analyzer/rust-analyzer/releases
And update every week or two manually

**Comment by filiptronicek** [comment]
@akosyakov should we remove the extension now because it's not working anyway and they are willing to go through with publishing directly?

**Comment by filiptronicek** [comment]
https://github.com/open-vsx/publish-extensions/commit/6afb8d3882f0e69128c5617f27836366cbed283e

**Comment by akosyakov** [comment]
@filiptronicek the mentioned commit seems to remove something else not matklad.rust-analyzer?

**Comment by filiptronicek** [comment]
@akosyakov fixed it, thanks for letting me know!
