### ISSUE TITLE
ms-pyright.pyright is out-of-date

### ISSUE THREAD

**Issue by yannl35133** [open-vsx/publish-extensions#528]
I don't know who publishes the extension here, but it is 20 versions late, and unfortunately for me one of them fixes a bug I am facing.

Could you publish the latest version ?

**Comment by filiptronicek** [comment]
@yannl35133 hopefully I fixed this in the linked PR, can you please double check you are no longer facing the issue at hand?

**Comment by yannl35133** [comment]
Thank you very much, that was very fast. I checked and the bug I had vanished, so it should be good

**Comment by filiptronicek** [comment]
It's 2AM here, love to fix bugs when I'm very tired, happy to help! 😄
