### ISSUE TITLE
Need ms-vscode-remote.remote-ssh

### ISSUE THREAD

**Issue by samweisgamdschie** [open-vsx/publish-extensions#530]
Hi!

At first, I am pretty happy seeing a project like this to be independent from MS, many thanks for that.

My question is, is it possible for you to add `ms-vscode-remote.remote-ssh` and the dependencies for remotely develop, debug and execute **python** scripts?

Best regards

**Comment by filiptronicek** [comment]
Hi there @samweisgamdschie, I appreciate your liking of the project!

> My question is, is it possible for you to add `ms-vscode-remote.remote-ssh` and the dependencies for remotely develop, debug and execute python scripts?

Sadly, this is not possible. For publishing to OpenVSX via this repository, the extension at hand has to be open-source and also have a license which is approved by the Open Source Initiative. This is not the case for many Microsoft-owned extensions, including the remote development toolkit, live share and others. Maybe one day they will open-source them, but who knows 😄.
