### ISSUE TITLE
Publish vscode-js-profile-table

### ISSUE THREAD

**Issue by xsrvmy** [open-vsx/publish-extensions#539]
`vscode-js-profile-table` is now a built-in extension, but it is not on openvsx. It is MIT licensed.

**Comment by filiptronicek** [comment]
I have now published the extension to Open VSX [[1](https://open-vsx.org/extension/ms-vscode/vscode-js-profile-table)], but have been struggling to make it work with publishing automatically. I will continue on trying, but until then there is the latest version published.
