### ISSUE TITLE
Publish znck.grammarly

### ISSUE THREAD

**Issue by jirutka** [open-vsx/publish-extensions#542]
It has been requested almost a year ago in upstream, but the author hasn’t responded yet: https://github.com/znck/grammarly/issues/184.

**Comment by akosyakov** [comment]
@filiptronicek it should be added to OpenVSX board correct?

**Comment by filiptronicek** [comment]
Yes, I will add it right away 👍

**Comment by filiptronicek** [comment]
Sorry for not following up earlier, but the extension has now been published by the author [[1](https://github.com/znck/grammarly/issues/184#issuecomment-1120529054)] 🚀, so it's now available.
