### ISSUE TITLE
alexkrechik extension auto publishing

### ISSUE THREAD

**Issue by alexkrechik** [open-vsx/publish-extensions#562]
Could you please disable alexkrechik cucumber extension auto publishing? This is required to get alexkrechik namespace ownership. More info could be foune [here](https://github.com/EclipseFdn/open-vsx.org/issues/924#issuecomment-1076701992).

**Comment by filiptronicek** [comment]
Hi there @alexkrechik, just wanted to say a big thanks for willing to publish the extension yourself, we really appretiate it.

I removed the extension from the list, you should be good to go now 🚀 :shipit:
