### ISSUE TITLE
Add Github Copilot extension

### ISSUE THREAD

**Issue by ment1na** [open-vsx/publish-extensions#595]

**Comment by filiptronicek** [comment]
Hey there @ment1na 👋! Thanks for reaching out about Copilot.

Sadly, GitHub Copilot is proprietary - the source code is private and so we cannot publish it. GitHub would have to do that themselves. 

Please feel free to contact GitHub to publish the extension to OpenVSX.

**Comment by felipecrs** [comment]
Question: if they publish the .vsix as a GitHub Release, would that be enough?

**Comment by filiptronicek** [comment]
I believe this is not enough, as just publishing as a GitHub Release still doesn't change the license of the software. Only way if Microsoft open-sources the extension and/or publishes it on their own would it be alright to publish to Open VSX.
