### ISSUE TITLE
broken `ms-python.python` builds due to missing translations

### ISSUE THREAD

**Issue by xaberus** [open-vsx/publish-extensions#604]
The `ms-python.python` extension now uses an "internal process" to build the VSIX. This process adds translation files that are missing from the regular build. In the regular build the missing files result in all translated strings becoming `Failed to load message bundle. See console for details.` [19280](https://github.com/microsoft/vscode-python/issues/19280)

The proposed solution is to set the `DISABLE_TRANSLATIONS` environment variable to disable the translations hook. I tested this locally and it seems to work.

**Comment by filiptronicek** [comment]
Thanks for raising the issue, @xaberus. For me it's sad to see the extension become more closed-off, and I many thanks for communicating your ideas with the folks at Microsoft.

I have linked a fixing PR, https://github.com/open-vsx/publish-extensions/pull/605. I will first try it out though to see if the artifact has built correctly.

Thanks a lot, again for taking care and communicating the issue 🙏.
