### ISSUE TITLE
VSCode RoyAction.color-manager Extension

### ISSUE THREAD

**Issue by wildernessfamily** [open-vsx/publish-extensions#648]
Hi, I've been using coder-server for about a month now for remote development. It's been amazing. There is one extension that I use often called color-manager. It's not published in Open VSX. Per your guidelines that state to contact the author first before submitted the request; which I have tried with no success.
Steps that I have taken:
1. I visited the official extension page: https://marketplace.visualstudio.com/items?itemName=RoyAction.color-manager&ssr=false#overview
2. I tried to ask a question on the official extension page which routes you to the GitHub pull request section where you 'can not' ask a question.
3. While on the repository on GitHub I tried to open an issue to ask the author. The repository has issues disabled. There is no way to open an issue.
4. Back on the official extension page I tried all three of the social links, Facebook, Twitter, and Email. The Facebook, and Twitter is just an extension that allows you to post on your page that you are using the said extension. The email link only opens an email with a prebuilt subject line. There is no email address.
5. I visited the authors GitHub page but could not find any links or any information in contacting the author. The author has only two repositories, both devoted to this extension, both with issues disabled. 

As a developer, I think it's common curiosity to ask said developer to publish their extension on another app/extension store. At this point I have no idea how to ask the author. Prior to moving forward, if you have any ideas I'm more than try to contact the author.
Thank you,

**Comment by filiptronicek** [comment]
Hey there @wildernessfamily 👋!

I am really amazed by the effort you put in to contacting the author 😄, I think we can sort this out by publishing automatically from here. I have commited the change to add the extension to the repo and will let you know when it is published.

**Comment by filiptronicek** [comment]
The extension has been published: https://open-vsx.org/extension/RoyAction/color-manager

**Comment by filiptronicek** [comment]
Thanks a lot for the efforts again, @wildernessfamily, glad to have the extension on Open VSX.

**Comment by wildernessfamily** [comment]
@filiptronicek Thank you for taking the time to review my request and add the extension. I really appreciate it. Thanks again!
