### ISSUE TITLE
missing, but defined extension rioj7.FileGroup

### ISSUE THREAD

**Issue by GitMensch** [open-vsx/publish-extensions#652]
After searching open-vsx.org for "fileGroup" and not finding it there I've checked in the original repo, got back to https://github.com/rioj7/fileGroup/issues/3, then tried the CI and was prompted with:

~~~
node add-extension.js https://marketplace.visualstudio.com/items?itemName=rioj7.FileGroup
Adding extension: {
  repository: 'https://github.com/rioj7/fileGroup'
}
Extension already defined: rioj7.FileGroup
~~~

... so something does not work

**Comment by filiptronicek** [comment]
Added the necessary dependency that was causing the extension to not publish: https://github.com/open-vsx/publish-extensions/commit/c0aff09d067db19cb3eee77e50542ab0372851c2.

**Comment by GitMensch** [comment]
Thanks. Now there's only one other extension from the same publisher which is hardly missing - but I can't that to build at all https://github.com/rioj7/command-variable/issues/44 :-/

**Comment by filiptronicek** [comment]
@GitMensch do you know whether we've asked the publisher to overtake publishing to Open VSX? Maybe that would be easier 🙂

**Comment by GitMensch** [comment]
We did both, see the referenced issue in the topic start.

**Comment by filiptronicek** [comment]
Ooooh, silly me, didn't spot the issue and forgot I even replied to it myself 😆.

The extension is published now btw! https://open-vsx.org/extension/rioj7/FileGroup
