### ISSUE TITLE
Publish pre-release channel for `ms-python.black-formatter`

### ISSUE THREAD

**Issue by yajo** [open-vsx/publish-extensions#653]
There's a problem with this extension. It's not working if your host uses python 3.11.

It's fixed in the pre-release: https://github.com/microsoft/vscode-black-formatter/issues/144#issuecomment-1295284755

Is there a way to publish a pre-release channel in open VSX too?

**Comment by filiptronicek** [comment]
Hey @yajo! Thanks for noticing and reporting this. I'll take a look soon because this looks like something we should resolve, but this repo does not do pre-releases as of now. 

Could do a manual one though, will get back to you here.

**Comment by filiptronicek** [comment]
@yajo I published https://open-vsx.org/extension/ms-python/black-formatter/2022.7.13271013, can you take a look to verify whether that solved the issue? 🙏

**Comment by yajo** [comment]
Yeah, so it seems. Thanks!
