### ISSUE TITLE
Add GitHub Copilot

### ISSUE THREAD

**Issue by felipecrs** [open-vsx/publish-extensions#657]
Because why not? I doubt they would publish it to OpenVSX by theirselves.

**Comment by filiptronicek** [comment]
Hey @felipecrs 👋! 

It would certainly be great to have Copilot on Open VSX, but the only holder of the license for the extension's source code is Microsoft. We don't have access to the source code and hence cannot built the extension. There are no other ways to download the packaged extension from Microsoft's VS Code Marketplace, which prohibits re-distribution of files downloaded from there.

Would certainly be great if Copilot would open-source their extension one day, and then we can re-open 🙂.

**Comment by filiptronicek** [comment]
Related: https://github.com/open-vsx/publish-extensions/issues/595

**Comment by felipecrs** [comment]
> Related: #595

Wow. I searched for existing issues before opening. Not sure how I let this pass, sorry about that. :(

**Comment by filiptronicek** [comment]
All good!

**Comment by xendren** [comment]
So we can use VS Code inside of Gitpod, but most of the useful extensions can't be used because Gitpod is dependent on the open-vsx registry?
