### ISSUE TITLE
[ms-python.python] Error: Extension python version 2020.2.3 is already published.

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#7]
```
 DONE  Packaged: /tmp/tmp-2582Nm2IlDoPhtoY.vsix (110 files, 371.7KB)

[FAIL] Could not process extension: {
  "id": "ms-python.python",
  "version": "2020.2.64397",
  "repository": "https://github.com/Microsoft/vscode-python",
  "checkout": "2020.2.64397"
}
Error: Extension python version 2020.2.3 is already published.
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jankeromnes** [comment]
- https://github.com/microsoft/vscode-python/blob/2020.2.64397/package.json#L5
  - expected: `"2020.2.64397"`
  - actual: `"2020.2.3"`

**Comment by spoenemann** [comment]
They seem to use a tag name strategy where the third part of the version differs from the actual version. But I haven't found any documentation on that.

**Comment by jankeromnes** [comment]
@spoenemann since we already provide the intended version in `extensions.json`, maybe we could enforce it, e.g. by editing `package.json` just before publishing with `ovsx`?

**Comment by spoenemann** [comment]
Yes, we could do that. But then we need to be very careful to choose the correct gitref corresponding to the version.

**Comment by jankeromnes** [comment]
`ms-python.python` was removed from `extensions.json` in https://github.com/open-vsx/publish-extensions/commit/784a105cbad5c15fa41b797cb6a30c48bf1550e4
