### ISSUE TITLE
About adding vscode-flake8

### ISSUE THREAD

**Issue by apollo13** [open-vsx/publish-extensions#702]
I'd like to add vscode-flake8 https://github.com/microsoft/vscode-flake8/ to OpenVSX. Since it is a microsoft project I am not sure if it makes much sense to ask them whether they want to publish it. Can I just go ahead and open a PR to this repo or what would be the recommended workflow here? It is MIT licensed so it should be fine to host on OpenVSX

**Comment by apollo13** [comment]
Especially with this answer https://github.com/microsoft/vscode-autopep8/issues/102#issuecomment-1577194008 I don't expect the answer for flake8 to be different and don't want to create noise on the upstream repo unless necessary.

**Comment by jeanp413** [comment]
Hi @apollo13, yes feel free to create a PR for vscode-flake8 and/or vscode-autopep8, I'll look into it early next week

**Comment by jeanp413** [comment]
Seems there's already a PR for vscode-autopep8 https://github.com/open-vsx/publish-extensions/pull/686

**Comment by apollo13** [comment]
Ok, added #704, I copied over the build commands from the `.github/actions` from the original repo, so those should work (and since it matches isort & black we should be safe).

**Comment by filiptronicek** [comment]
Aaaaand... published: https://open-vsx.org/extension/ms-python/flake8
