### ISSUE TITLE
Isort misses bundled libs

### ISSUE THREAD

**Issue by apollo13** [open-vsx/publish-extensions#711]
The https://open-vsx.org/extension/ms-python/isort extension misses the bundled libraries. @filiptronicek (I hope it's okay to ping you for such things) is there a way to find out which action run published the extension to see whether or not there have been errors.

Also since isort as of now still uses python 3.7 we could try if the publishing workflow can install python3.7 and python3.8 side-by-side. But at the end of the day we would require to republish isort -- is that somehow possible?

**Comment by apollo13** [comment]
So isort uploaded from here apparently https://github.com/open-vsx/publish-extensions/actions/runs/6158978232/job/16712855282

**Comment by apollo13** [comment]
Attached is a build from my PC that works -- though I fully understand if you don't want to pull that in. It is built from tag v2023.11.12711013 [isort.zip](https://github.com/open-vsx/publish-extensions/files/12830712/isort.zip)

**Comment by filiptronicek** [comment]
Very well, I built the extension incorrectly on Python 3.11 instead of 3.7. Thanks, @apollo13, for looking into it! 

<img width="532" alt="image" src="https://github.com/open-vsx/publish-extensions/assets/29888641/6de7d349-176c-4bcc-83e5-7a9fff13e91b">

I am pushing a hack for the extension to use 3.7 when publishing, but will introduce an optional `pythonVersion` property for extensions sometime next week. Will also look into unpublishing the current one so that it can be replaced.

**Comment by apollo13** [comment]
Thank you for your hard work. `pythonVersion` sounds like a good idea. I wonder though if it might be easier to just call the setup python action twice? I think the second run will leave the first python version around and mostly replace the python symlink. But I'll leave it up to you to decide what you think would be better (maybe performance/timings of the action run should be a consideration?)

**Comment by filiptronicek** [comment]
@apollo13 I have republished `ms-python.isort` v2023.10.1. Could you check it out and see if it okay now? 🙏

**Comment by apollo13** [comment]
@filiptronicek Could there be a caching issue, or does keep vscode the downloaded files locally? If I manually download the vsix it has `/extension/bundled/libs/` -- but if I install it via codium it doesn't have it.

**Comment by apollo13** [comment]
Ah yes, `.config/VSCodium/CachedExtensionVSIXs`. After uninstalling the extension, stopping code and removing the cached vsix I could properly reinstall. Thx!
