### ISSUE TITLE
vscode-java-test plugin is outdated

### ISSUE THREAD

**Issue by WildPenquin** [open-vsx/publish-extensions#715]
Hi,

vscode-java-test plugin is outdated in open-vsx. The [currently available plugin](https://open-vsx.org/extension/vscjava/vscode-java-test) does not work correctly with currently available [java plugin](https://open-vsx.org/extension/redhat/java).

Also see: https://github.com/redhat-developer/vscode-java/issues/3338

**Comment by filiptronicek** [comment]
Thanks for the report, @WildPenquin, looking into this now.

**Comment by filiptronicek** [comment]
This looks like a server issue on https://open-vsx.org's part – we already tried to publish vscode-java-test@0.40.0 several times, but it seems the server is rejecting it. [[CI run](https://github.com/open-vsx/publish-extensions/actions/runs/6509473664/job/17681573839#step:12:25367)]

I will forward this to the folks responsible and update here when I have an update

**Comment by filiptronicek** [comment]
@WildPenquin could you try installing the extension again? I have published `0.40.0` now, which should be alright.

**Comment by WildPenquin** [comment]
0.40.0 is available now in the repos in my end and can be installed as expected.

Thanks!
