### ISSUE TITLE
better toml has to be deprecated

### ISSUE THREAD

**Issue by goyalyashpal** [open-vsx/publish-extensions#718]
screenshot from vs code i.e. using proprietary ms store

![image](https://github.com/open-vsx/publish-extensions/assets/19423063/924133a6-3fa8-44df-8c43-bdfbf2a9145a)

**Comment by filiptronicek** [comment]
Hi there @goyalyashpal 👋.
Currently, Open VSX (nor the VS Code Marketplace) have deprecated extension functionality built into them. This is a separate concern of a so-called control manifest, which instructs VS Code about the availability of different extensions. https://open-vsx.org has no official one yet ([proposal pending](https://github.com/EclipseFdn/open-vsx.org/issues/1121)), but Gitpod maintains a fairly up-to-date one in their repo [here](https://github.com/gitpod-io/gitpod/blob/main/components/ide-proxy/static/code/marketplace.json). 

You can add it by changing your VS Code's `product.json` file, like Gitpod does [here](https://github.com/gitpod-io/openvscode-server/blob/b901dc9f388d03c4075316d5e47548fc7d958046/product.json#L698C18-L698C61).

**Comment by goyalyashpal** [comment]
hi again. how can i do that? i tried looking up, but couldn't find any definitive steps. i am using vscodium 1.84 on win 10

**Comment by goyalyashpal** [comment]
> Currently, Open VSX (nor the VS Code Marketplace) have deprecated extension functionality built into them.

[vsx-depr-extsn]: https://blogs.eclipse.org/post/john-kellerman/new-feature-open-vsx-deprecating-extensions "New Feature in Open VSX: Deprecating Extensions | Eclipse Foundation Staff Blogs"

Glad it finally landed :)
I was stumbling on way tooo many old abandoned/unmaintained extensions lately.


[better-toml]: https://open-vsx.org/vscode/item?itemName=bungcip.better-toml "better-toml"

@filiptronicek can you please "close this issue as completed"?  as this [better-toml] extension is now rightly been marked deprecated on open--vsx too.


----

> Open VSX now supports deprecating extensions - see our [announcement](https://blogs.eclipse.org/post/john-kellerman/new-feature-open-vsx-deprecating-extensions).
>
> Wednesday, 2024 October 30 - 14:08 by John Kellerman
> \- _[New Feature in Open VSX: Deprecating Extensions | Eclipse Foundation Staff Blogs][vsx-depr-extsn]_
