### ISSUE TITLE
Publish fnando.linter

### ISSUE THREAD

**Issue by jirutka** [open-vsx/publish-extensions#737]
It has been requested almost a year ago in upstream, but the author hasn’t responded yet: https://github.com/fnando/vscode-linter/issues/27.

**Comment by jirutka** [comment]
@filiptronicek, can you please add this extension?

**Comment by filiptronicek** [comment]
Hey @jirutka, I have just published the extension: https://open-vsx.org/extension/fnando/linter. Let me know if there's any issues
