### ISSUE TITLE
Add the `swyddfa.esbonio` extension

### ISSUE THREAD

**Issue by tchernobog** [open-vsx/publish-extensions#741]
Add the extension from https://marketplace.visualstudio.com/items?itemName=swyddfa.esbonio.

This is increasingly becoming a replacement for `lextudio.restructuredtext`.

**Comment by filiptronicek** [comment]
Hey there @tchernobog, it seems the extension has been published in the meantime: https://open-vsx.org/extension/swyddfa/esbonio
