### ISSUE TITLE
Add the `ms-python.debugpy` extension

### ISSUE THREAD

**Issue by omhomurlu** [open-vsx/publish-extensions#743]
Looks like this extension started to make releases. It's currently an unsatisfied bundle dependency of most popular `ms-python.python` extension on open-vsx. IMHO, it's good to have it because, new debugging features will be added to this extension and not to the main python extension. It may also be possible to use it with alternative python extensions.

**Comment by filiptronicek** [comment]
Just published it, thanks for the report.
https://open-vsx.org/extension/ms-python/debugpy
