### ISSUE TITLE
remove extension IBM/clearcase as created by mistake

### ISSUE THREAD

**Issue by osmanburucu-ibm** [open-vsx/publish-extensions#751]
Hello some months ago i mistakingly created an extension (was learning how to use this site). As we do not support Codium or Theia at the moment I do need to get it removed.
Here the URL: https://open-vsx.org/extension/IBM/clearcase

Thank You in advance!

**Comment by filiptronicek** [comment]
Hi @osmanburucu-ibm, I have forwarded the request to https://github.com/EclipseFdn/open-vsx.org/issues/2463, where there should be someone to help. Closing this issue here, so feel free to track that new one.

**Comment by osmanburucu-ibm** [comment]
@filiptronicek  Thank You for your very fast reply and help!
