### ISSUE TITLE
The 'Python Debugger' extension is not available in VSCodium for Mac

### ISSUE THREAD

**Issue by elixirbeats** [open-vsx/publish-extensions#776]
As the title states, this extension does not work for vs codium on a macbook pro intel. I've searched around and not found other issues mentioning this..

**Comment by filiptronicek** [comment]
Hi @elixirbeats, I just manually published https://open-vsx.org/extension/ms-python/debugpy/2024.8.0. Can you please try again?

**Comment by elixirbeats** [comment]
yup working now, thank you!
