### ISSUE TITLE
Publish `DuckyScriptCookbook` to Open VSX

### ISSUE THREAD

**Issue by aleff-github** [open-vsx/publish-extensions#781]
Please publish this extension [1] to the Open VSX marketplace.

## The Extension

DuckyScript Cookbook is a simple yet powerful VSCode extension that helps you speedily paste ready-made DuckyScript snippets into your text files. Whether you're a coding newbie or a seasoned pro, we've got the right recipe to spice up your scripting experience!

![in action](https://github.com/aleff-github/Deposito/raw/main/DuckyScriptCookbook/Ducky-Script-Cookbook.gif?raw=true)

## Some Links

- **Extension Repository**[1]: [DuckyScriptCookbook](https://github.com/aleff-github/DuckyScriptCookbook/)
- **LICENCE**: [GPLv3](https://github.com/aleff-github/DuckyScriptCookbook/?tab=GPL-3.0-1-ov-file#readme) obv 😘
- **Official vsix file in the release**: [Release Page](https://github.com/aleff-github/DuckyScriptCookbook/releases/tag/1.0.0)

**Comment by filiptronicek** [comment]
Hi there @aleff-github 👋, this repository is made for extensions whose authors are unable to publish to Open VSX themselves. It looks like the extension you linked is in fact an extension that you made and maintain, so I'd like to ask you to follow https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md and setup publishing on your side.

If there's anything more you need surrounding publishing, don't hesitate to reach out.
