### ISSUE TITLE
[add-extension] Improve extension `package.json` location detection

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#80]
When you do `node add-extension https://...`, and the extension's `package.json` is not in the root of the repo, sometimes the [current `location` auto-detection](https://github.com/open-vsx/publish-extensions/blob/8e0c2bef037591d489d1c462cc6f753e927d9d05/add-extension.js#L63-L73) fails:

```
gitpod /workspace/publish-extensions $ node add-extension.js https://github.com/apollographql/apollo-tooling
Running: git clone --recurse-submodules https://github.com/apollographql/apollo-tooling /tmp/repository
Running: ls package.json 2>/dev/null || git ls-files | grep package\.json
[FAIL] Could not add https://github.com/apollographql/apollo-tooling!
Error: Expected "publisher" in ./package.json: {
  "name": "apollo-tooling-monorepo",
  "private": true,
  "homepage": "https://github.com/apollographql/apollo-tooling",
  "bugs": "https://github.com/apollographql/apollo-tooling/issues",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/apollographql/apollo-tooling.git"
  },
  "license": "MIT",
...
```

It would be cool to improve the location detection, e.g. by searching for a `package.json` that contains the work `publisher` (more likely to find the right `package.json` in a big monorepo).

**Comment by filiptronicek** [comment]
I'm closing this as we no longer have an `add-extension` script.
