### ISSUE TITLE
[Ionide.Ionide-fsharp] Error: Cannot resolve dependency: ms-dotnettools.csharp

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#83]
> https://github.com/open-vsx/publish-extensions/blob/fda76b4c0dc125a4c5e372b417181a31985dc0f3/extensions.json#L376-L382
> 
> It's currently in this repository's auto-publish list, however, the nightly publishing job currently fails every day with this error:
> 
> ```
> Error: Cannot resolve dependency: ms-dotnettools.csharp
> ```
> 
> And indeed, `ms-dotnettools.csharp` is itself not on OpenVSX, because its [license](https://github.com/OmniSharp/omnisharp-vscode/blob/master/RuntimeLicenses/license.txt) forbids it. (Note: Even though the OmniSharp respository is itself under MIT license, the extension's `package.json` [explicitly points to](https://github.com/OmniSharp/omnisharp-vscode/blob/6868a02014d91b59c52bb7994f794530a339a35b/package.json#L8) Microsoft's incompatible license.)
> 
> Thus, while it was okay to add `Ionide.Ionide-fsharp` to our auto-publish list, publishing can never succeed as long as it depends on an incompatible extension, and that's why you won't find an FSharp extension on https://open-vsx.org today (which is quite sad).

[Source](https://github.com/open-vsx/publish-extensions/issues/81#issuecomment-657693685)

**Comment by muhammadsammy** [comment]
Hello @jankeromnes!
[This extension](https://open-vsx.org/extension/muhammad-sammy/csharp) can be used instead.
It's a free version of the official C# extension and the ionide extension works fine with it (except the debugger as it's proprietary).

**Comment by jankeromnes** [comment]
This extension was removed from this repository in https://github.com/open-vsx/publish-extensions/commit/7ec4fe6327c382c983bdf37e825f5a4930ac55ec because the namespace `Ionide` was claimed in https://github.com/eclipse/open-vsx.org/issues/134.
