### ISSUE TITLE
[vscjava.vscode-java-debug] Missing Java Debug Server in packaged extension

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#84]
`vscjava.vscode-java-debug-0.25.1.vsix` is 119K on OpenVSX, while it should be 2.5M instead:

https://open-vsx.org/extension/vscjava/vscode-java-debug

The reason is that the Java Debug Server accidentally wasn't packaged into the extension, resulting in a broken extension. This problem has since been fixed in https://github.com/open-vsx/publish-extensions/commit/ec76ea73181b0bd185a38777cc6e5cf0c5e4a1b0.

@jbicker or @spoenemann, could you please delete all currently live versions of this extension (both `0.25.1` and `0.26.0`), so that fixed versions can be uploaded by our script?

**Comment by spoenemann** [comment]
I deleted version `0.26.0`. I cannot delete all versions because the following extensions depend on the extension: `vscjava.vscode-java-test`, `redhat.vscode-quarkus`

**Comment by jankeromnes** [comment]
@spoenemann Thanks! Then I will publish a new, fixed `0.26.0` version, and then we can delete the broken `0.25.1` version, and then I can re-publish a fixed extension for that version too.

**Comment by jankeromnes** [comment]
Done, a fixed `0.26.0` has been published: https://open-vsx.org/extension/vscjava/vscode-java-debug, and its download size is 2.5MB as expected.

@spoenemann Please delete version `0.25.1` so that I can re-publish it as well.

**Comment by spoenemann** [comment]
> Please delete version 0.25.1 so that I can re-publish it as well.

done.

**Comment by jankeromnes** [comment]
Awesome, thanks, and `0.25.1` should now be fixed as well! 🎉

<img width="375" alt="Screenshot 2020-07-20 at 11 55 31" src="https://user-images.githubusercontent.com/599268/87925066-08c56400-ca80-11ea-8d94-70fd53711385.png">
