### ISSUE TITLE
PlatformIO not on open-vsx.org although merged in this repo (Error: Cannot resolve dependency: ms-vscode.cpptools)

### ISSUE THREAD

**Issue by 54696d21** [open-vsx/publish-extensions#86]
Why doesn't Platformio not appear on open-vsx.org although it was merged in #54?

**Comment by jankeromnes** [comment]
Hi @54696d21, good catch! We missed this problem.

The latest publishing GitHub Action logs say:

```
[FAIL] Could not process extension: {
  "id": "platformio.platformio-ide",
  "repository": "https://github.com/platformio/platformio-vscode-ide",
  "version": "1.10.0",
  "checkout": "v1.10.0"
}
Error: Cannot resolve dependency: ms-vscode.cpptools
    at Object.<anonymous> (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:52:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/publish-extensions/publish-extensions/node_modules/ovsx/lib/publish.js:14:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The solution would be to add `ms-vscode.cpptools` to OpenVSX as well (if its license allows it).

**Comment by jankeromnes** [comment]
Ah, unfortunately, at first glance https://github.com/microsoft/vscode-cpptools/blob/master/Extension/LICENSE.txt doesn't seem to be compatible with OpenVSX.

**Comment by 54696d21** [comment]
ok, that's unfortunate. I'm impressed how restrictive that license is.

**Comment by noah1510** [comment]
That extention recycled parts from visual studio, so it inherited its license.
It seems like the developers/maintainers can't do anything about that see [here](https://github.com/Microsoft/vscode-cpptools/issues/21#issuecomment-248349017).

I opened [this](https://github.com/platformio/platformio-vscode-ide/issues/1940) issue about changing the language server to clangd.
According to [this](https://github.com/platformio/platformio-core/issues/2990) issue platformio can generate a compile_commands.json file, which would make an integration with clangd a lot more simple.

**Comment by yunuscukran** [comment]
> According to [this](https://github.com/platformio/platformio-core/issues/2990) issue platformio can generate a compile_commands.json file, which would make an integration with clangd a lot more simple.

From my understanding, the [existence](https://clang.llvm.org/docs/JSONCompilationDatabase.html) of a `compile_commands.json` at the top is enough for [lvm-vs-code-extensions.vscode-clangd](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd) to work, and PlatformIO can already [generate](https://docs.platformio.org/en/latest/integration/compile_commands.html) a `compile_commands.json`. Can anyone confirm if this is all that's required to make PIO work with the clang server?

**Comment by noah1510** [comment]
>  Can anyone confirm if this is all that's required to make PIO work with the clang server?

I have not tested it with the `compile_commands.json` produced by PIO but it works without any problems with meson, which also just creates a `compile_commands.json` for clangd to use.
It should work just fine assuming the produced file has the correct universal format, which it should have.

**Comment by yunuscukran** [comment]
> > Can anyone confirm if this is all that's required to make PIO work with the clang server?
> 
> I have not tested it with the `compile_commands.json` produced by PIO but it works without any problems with meson, which also just creates a `compile_commands.json` for clangd to use.
> It should work just fine assuming the produced file has the correct universal format, which it should have.

I have tested it with `compile_commands.json`. It **almost** works fine. The libraries that are externally downloaded as PlatformIO packages ( so no .h files in the include dir, only .o files in the build directories) can't be parsed, while the Microsoft language server was able to do this.

If this problem is solved, it is my understanding that PlatformIO is very close to be `open-vsx` compatible through using `clang` language server.

**Comment by RussellAult** [comment]
Has anyone checked the license on ms-vscode.cpptools recently? The link above 404s now, and the only license I can find there was https://github.com/microsoft/vscode-cpptools/blob/master/LICENSE.md , which is MIT...

**Comment by spoenemann** [comment]
@RussellAult the runtime license has moved here:

**Comment by RussellAult** [comment]
Right, but it sounds like according to microsoft/vscode-cpptools#5857 that the restrictive license is what applies to the Microsoft Marketplace binaries; the source code itself is under MIT.

**Comment by spoenemann** [comment]
Yes, you can fork the MIT licensed code and publish it to a different namespace if you want. But I don't know whether it's possible to create a version of that extension that does not depend on any Microsoft proprietary stuff. The extension downloads lots of content listed in `"runtimeDependencies"`:
https://github.com/microsoft/vscode-cpptools/blob/e41b32c5cd738454299b822d8132b461d1932321/Extension/package.json#L2336-L2573

**Comment by RussellAult** [comment]
...at least one of which ("C/C++ language components") I can't even find the source for. Right, never mind. Sorry everyone!

**Comment by ivankravets** [comment]
Hi all,

This is Ivan, the @PlatformIO founder. Microsoft C/C++ extension is licensed under MIT. I still trust it was a "typo" by Microsoft management. See my comment here https://github.com/microsoft/vscode-cpptools/issues/6388#issuecomment-720109512 

We did know that the MIT license was the "screen" to hell. If that is true, we will stop using that extension.

**Comment by spoenemann** [comment]
Hi @ivankravets, with https://github.com/eclipse/open-vsx.org/issues/197 I assume you are going to work on publishing yourself and we can remove the platformio entry from this auto-publishing list?

**Comment by ivankravets** [comment]
Hi @spoenemann,

Thanks for approving our account. Yes, we would like to publish our extension to Open VSX but there is a dependency on C/C++ extension. We work on the soltuion for this issue.

Sorry, we didn't know that Microsoft C/C++ extension is not MIT licensed as they claim on Github. You can read more at https://github.com/microsoft/vscode-cpptools/issues/6388#issuecomment-721386780

We posted a temporary solution for this case at https://github.com/platformio/platformio-vscode-ide/issues/1802

**Comment by spoenemann** [comment]
Ok, removed the entry here: https://github.com/open-vsx/publish-extensions/commit/4bc99a2b8747a7bfa898aa382e0929a2ef014ffd

**Comment by marcdumais-work** [comment]
Hi @ivankravets 

> We work on the soltuion for this issue.

I hope you can switch to `vscode-clangd` ASAP - it's rapidly improving and gaining features, as is `clangd`. I have asked one of our contributors an update about one of your two blocking issues - I hope he can help. 

Coming together and collaborating, us non-Visual-Studio product/framework makers, open registry provider and extension consumers, to offer a better solution, vs the superficiallty-FOSS (really proprietary) extension, that we can't use anyway, is the best thing we can do.

**Comment by ivankravets** [comment]
Hi @marcdumais-work ,

Please move your comment to https://github.com/platformio/platformio-vscode-ide/issues/1802

Happy to discuss how can we solve this issue ASAP.
