### ISSUE TITLE
[ms-vscode.node-debug] Missing 'dist' folder in packaged extension

### ISSUE THREAD

**Issue by jankeromnes** [open-vsx/publish-extensions#88]
As reported by @marcdumais-work in https://open-vsx.org/extension/ms-vscode/node-debug/reviews:

> The vsix is missing some `dist` folder (that should contain the javascript executable code).

It would be good to figure out how this missing `dist` folder can be added to the published extension, and then delete the broken extensions from https://open-vsx.org

**Comment by jankeromnes** [comment]
Note: This is how we currently auto-publish this extension:

https://github.com/open-vsx/publish-extensions/blob/dae1cfb57e61fae3677a33ea1e190200510710e8/extensions.json#L554-L559

**Comment by spoenemann** [comment]
I'd try `yarn prepublish && yarn package`:

https://github.com/microsoft/vscode-node-debug/blob/4b2d2ca0dbe3bec12649a90c40bd0e2c904c0ca0/package.json#L16-L27

**Comment by jankeromnes** [comment]
Thanks! I'll try that.

**Comment by jankeromnes** [comment]
Oops, chose the word "resolve" instead of "fix", in order not to auto-close this issue yet, but apparently GitHub understands "resolve" as well.

**Comment by jankeromnes** [comment]
That seems to have worked: https://open-vsx.org/extension/ms-vscode/node-debug/1.44.5 now has the `dist` folder.

@spoenemann Could you please delete `ms-vscode.node-debug` versions `1.35.3`, `1.38.4`, `1.41.1`, and `1.44.7`? (I.e. everything except `1.44.5`)

Then I'll re-publish these versions too.

**Comment by spoenemann** [comment]
Done.

**Comment by marcdumais-work** [comment]
Thanks!
