### ISSUE TITLE
Puppet extension

### ISSUE THREAD

**Issue by heylix** [open-vsx/publish-extensions#90]
You can install the [puppet.puppet-vscode extension](https://marketplace.visualstudio.com/items?itemName=puppet.puppet-vscode) by downloading the .vsix from the Microsoft VSCode marketplace. It throws a few warnings but still works.

They're also tracking this issue over there: https://github.com/puppetlabs/puppet-vscode/issues/690

This was previously [jpogran.puppet-vscode](https://marketplace.visualstudio.com/items?itemName=jpogran.puppet-vscode).

**Comment by spoenemann** [comment]
> You can install the puppet.puppet-vscode extension by downloading the .vsix from the Microsoft VSCode marketplace.

See the VS Code Marketplace [Terms of Use](https://aka.ms/vsmarketplace-ToU):

> Marketplace Offerings are intended for use only with Visual Studio Products and Services

**Comment by spoenemann** [comment]
For this reason, we always publish extensions from their GitHub source instead of using the .vsix from the Marketplace.

**Comment by heylix** [comment]
> See the VS Code Marketplace [Terms of Use](https://aka.ms/vsmarketplace-ToU):
> 
> > Marketplace Offerings are intended for use only with Visual Studio Products and Services

Yes, I know, I just wanted to say that it works in vscodium.

**Comment by jankeromnes** [comment]
... but what is the issue?

If this is a request to publish the Puppet extension to https://open-vsx.org, I'm happy to take a look.

**Comment by jankeromnes** [comment]
Puppet extension should now get published to https://open-vsx.org during the next CI run (usually at 03:03 UTC).

Will post back here once we know if it worked or not.
